const shoeList = [      
    { shoe: 'black-wedge',
      price: 350, size: 7, 
      in_stock: 5, 
      color: 'black',
   },
{ shoe: 'cinderella-nikes',
  price: 275,
   size: 10, 
   in_stock: 4,
   color: 'blue',  },
{  shoe: 'crocs-sneakers',
 price: 350,
  size: 7,
   in_stock: 12,
   color: 'white',},
{  shoe: 'crossover-heal', 
price: 450, 
size: 6, in_stock:
 8, color: 'red',},
{  shoe: 'ladys-boots',
 price: 275, 
 size: 9, 
 in_stock: 6,
 color: 'grey', },
{  shoe: 'woderland-vans', 
price: 275,
 size: 9, 
 in_stock: 6,
  color: 'white',}];